// User reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';
// UI reducer types
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';
// Data reducer types
export const SET_INTERNSHIPS = 'SET_INTERNSHIPS';
export const SET_INTERNSHIP = 'SET_INTERNSHIP';
export const LIKE_INTERNSHIP = 'LIKE_INTERNSHIP';
export const UNLIKE_INTERNSHIP = 'UNLIKE_INTERNSHIP';
export const DELETE_INTERNSHIP = 'DELETE_INTERNSHIP';
export const INTERNSHIP_INTERNSHIP = 'INTERNSHIP_INTERNSHIP';
export const ADD_INTERNSHIP = 'ADD_INTERNSHIP';
export const SUBMIT_COMMENT = 'SUBMIT_COMMENT';

export const GET_COMMENT_SUCCESS = 'GET_COMMENT_SUCCESS';
export const GET_COMMENT_FAILURE = 'GET_COMMENT_FAILURE';
export const GET_SUPERVISOR = 'GET_SUPERVISOR';
